routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use \App\{Post, PostImage};

Route::get('/', function () {
    //$users = \App\User::all();
    return view('welcome', ['test' => 'Nanderson']);
});

Route::get('sub', function(){
    $posts =  Post::addSelect([
        'thumb' => PostImage::select('image')
                            ->whereColumn('post_id', 'posts.id')
                            ->limit(1)
    ])->get();

    return $posts;
});

Route::get('lazy-collections', function(){
    $posts = Post::cursor(); //Retornar pra gente uma LazyCollection...
    //dd($posts);
    foreach($posts as $post){
        print $post->title . '<br>';
    }
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Rotas para trabalho em nosso CRUD de Posts
Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'description'];

    public function post_images()
    {
        return $this->hasMany(PostImage::class);
    }
}

app/PostImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PostImage extends Model
{
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class PostController extends Controller
{
    private $post;

    public function __construct(Post $post)
    {
        $this->post = $post;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->post->orderBy('id', 'DESC')->paginate(30);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $data = $request->all();
            // Criando post usando Active Record
            // $post = $this->post;
            // $post->title = $data['titulo_alguma'];
            // $post->description = $data['description'];

            // $post->save();
            //Criando post usando Mass Assignment
            $post = $this->post->create($data);

            flash('Post criado com sucesso!')->success();
            return redirect()->route('posts.index');

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();

                return redirect()->back();
            }

            flash('Post não foi criada com sucesso!')->warning();
            return redirect()->back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try{
            $post = $this->post->findOrFail($id);

            return view('posts.edit', compact('post'));

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();
                return redirect()->back();
            }

            flash('Post não encontrado...')->warning();
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $data = $request->all();

            $post = $this->post->findOrFail($id);
            $post->update($data);

            flash('Post atualizado com sucesso!')->success();
            return redirect()->route('posts.index');

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();
                return redirect()->back();
            }
            flash('Post não foi atualizado...')->warning();
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            $post = $this->post->findOrFail($id);
            $post->delete();

            flash('Post removido com sucesso!')->success();
            return redirect()->route('posts.index');

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();
                return redirect()->back();
            }

            flash('Post não pode ser removido...')->warning();
            return redirect()->back();
        }
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @include('flash::message')

            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/Index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <a href="{{route('posts.create')}}" class="btn btn-lg btn-success">Criar Postagem</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Titulo</th>
                <th>Criado em</th>
            </tr>
        </thead>
        <tbody>
            @forelse($posts as $post)
            <tr>
                <td>{{$post->id}}</td>
                <td>
                    <a href="{{route('posts.show', ['post' => $post->id])}}">
                    {{$post->title}}
                    </a>
                </td>
                <td>{{$post->created_at}}</td>
            </tr>
            @empty
                <tr>
                    <td colspan="3">
                        <h2>Nenhum post encontrado!</h2>
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
    {{$posts->links()}}
@endsection

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('posts.store')}}" method="post">
        <!-- <input type="hidden" name="_token" value="{{csrf_token()}}"> -->

        {{-- csrf_field() --}}

        @csrf

        <div class="form-group">
            <label>Titulo</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label>Descrição</label>
            <textarea name="description" cols="30" rows="10" class="form-control"></textarea>
        </div>

        <button type="submit" class="btn btn-lg btn-success">Criar Post</button>
    </form>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('posts.update', ['post' => $post->id])}}" method="post">
        <!-- <input type="hidden" name="_token" value="{{csrf_token()}}"> -->

        {{-- csrf_field() --}}

        @csrf
        @method("PUT")
        <div class="form-group">
            <label>Titulo</label>
            <input type="text" class="form-control" name="title" value="{{$post->title}}">
        </div>
        <div class="form-group">
            <label>Descrição</label>
            <textarea name="description" cols="30" rows="10" class="form-control">{{$post->description}}</textarea>
        </div>

        <button type="submit" class="btn btn-lg btn-success">Atualizar Post</button>
    </form>
    <hr>

    <form action="{{route('posts.destroy', ['post' => $post->id])}}" method="post">
        @csrf
        @method('DELETE')

        <button type="submit" class="btn btn-lg btn-danger">Remover Post</button>
    </form>

@endsection